absl-py==0.12.0
alabaster==0.7.12
appdirs==1.4.4
astroid==2.5.6
astunparse==1.6.3
atomicwrites==1.4.0
attrs==21.2.0
autodocsumm==0.2.4
babel==2.9.1
backcall==0.2.0
bayesian-optimization==1.2.0
beautifulsoup4==4.9.3
black==20.8b1
bleach==3.3.0
brotli==1.0.9
cachetools==4.2.2
cdt==0.5.23
chardet==4.0.0
click==8.0.0
cloudpickle==1.6.0
cma==3.0.3
colorama==0.4.4
commonmark==0.9.1
coverage==5.5
cycler==0.10.0
decorator==4.4.2
docutils==0.16
et-xmlfile==1.1.0
fcmaes==1.2.18
flask==2.0.0
flask-compress==1.9.0
future==0.18.2
gast==0.3.3
google-auth==1.30.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
gputil==1.4.0
grpcio==1.37.1
gym==0.18.3
h5py==2.10.0
hiplot==0.1.24
hyperopt==0.2.5
idna==2.10
image-quality==1.2.6
imageio==2.9.0
imagesize==1.2.0
importlib-metadata==4.0.1
iniconfig==1.1.1
iohexperimenter==0.2.8.7
ipython==7.23.1
ipython-genutils==0.2.0
isort==5.8.0
itsdangerous==2.0.0
jedi==0.18.0
jinja2==2.11.3
joblib==1.0.1
keras==2.2.4
keras-applications==1.0.8
keras-preprocessing==1.1.2
keyring==23.0.1
kiwisolver==1.3.1
koncept==0.2.2
kuti==0.9.7
lazy-object-proxy==1.6.0
libsvm==3.23.0.4
lpips==0.1.3
markdown==3.3.4
markupsafe==1.1.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
mccabe==0.6.1
mixsimulator==0.3.3
munch==2.5.0
mypy==0.812
mypy-extensions==0.4.3
networkx==2.5.1
nose==1.3.7
numpy==1.18.5
oauthlib==3.1.0
opencv-python==4.1.2.30
openpyxl==3.0.7
opt-einsum==3.3.0
packaging==20.9
pandas==1.2.4
parso==0.8.2
pathspec==0.8.1
patsy==0.5.1
pickleshare==0.7.5
pillow==7.2.0
pkginfo==1.7.0
pluggy==0.13.1
ply==3.11
prompt-toolkit==3.0.18
protobuf==3.17.0
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyglet==1.5.15
pygments==2.9.0
pylint==2.8.2
pyomo==5.7.3
pyparsing==2.4.7
pyproj==3.0.1
pytest==6.2.4
pytest-cov==2.12.0
python-dateutil==2.8.1
pytz==2021.1
pyutilib==6.0.0
pywavelets==1.1.1
pywin32-ctypes==0.2.0
pyyaml==5.4.1
readme-renderer==29.0
recommonmark==0.7.1
regex==2021.4.4
requests==2.25.1
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
rfc3986==1.5.0
rsa==4.7.2
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.6.3
six==1.16.0
skrebate==0.62
snowballstemmer==2.1.0
soupsieve==2.2.1
sphinx==4.0.1
sphinx-rtd-theme==0.5.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
statsmodels==0.12.2
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.3.2
tensorflow-estimator==2.3.0
termcolor==1.1.0
threadpoolctl==2.1.0
toml==0.10.2
torch==1.8.1
torchvision==0.9.1
tqdm==4.60.0
traitlets==5.0.5
twine==3.4.1
typed-ast==1.4.3
typing-extensions==3.10.0.0
urllib3==1.26.4
wcwidth==0.2.5
webencodings==0.5.1
werkzeug==2.0.1
wrapt==1.12.1
xlrd==2.0.1
xlwt==1.3.0
zipp==3.4.1
